// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqL74yMxVrazLyGUwweyTIG3dfEKCCo84',
    appId: '1:876719111475:web:88d894c9b5f905d9fb5246',
    messagingSenderId: '876719111475',
    projectId: 'surtte-4bf22',
    authDomain: 'surtte-4bf22.firebaseapp.com',
    storageBucket: 'surtte-4bf22.firebasestorage.app',
    measurementId: 'G-6FD57M3Y7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vLDcmBoWmCGbm9SAJLBJvu69mqS5ZyY',
    appId: '1:876719111475:android:75199ca8fa63fe07fb5246',
    messagingSenderId: '876719111475',
    projectId: 'surtte-4bf22',
    storageBucket: 'surtte-4bf22.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcj18TxEnWBOfO3eIopBTUGeTV1X--YkA',
    appId: '1:876719111475:ios:1f5a0dd9275f7185fb5246',
    messagingSenderId: '876719111475',
    projectId: 'surtte-4bf22',
    storageBucket: 'surtte-4bf22.firebasestorage.app',
    androidClientId: '876719111475-btv5apdrp2n8l7960q5jqnqbqnthas5k.apps.googleusercontent.com',
    iosClientId: '876719111475-csvj9ah24e5fs9om1ha1gbs5i97nbokn.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcj18TxEnWBOfO3eIopBTUGeTV1X--YkA',
    appId: '1:876719111475:ios:1f5a0dd9275f7185fb5246',
    messagingSenderId: '876719111475',
    projectId: 'surtte-4bf22',
    storageBucket: 'surtte-4bf22.firebasestorage.app',
    androidClientId: '876719111475-btv5apdrp2n8l7960q5jqnqbqnthas5k.apps.googleusercontent.com',
    iosClientId: '876719111475-csvj9ah24e5fs9om1ha1gbs5i97nbokn.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOw-msciy7clZLUuCpczduaDkZ9ZRpHIY',
    appId: '1:876719111475:web:c320b3703cf1f8fefb5246',
    messagingSenderId: '876719111475',
    projectId: 'surtte-4bf22',
    authDomain: 'surtte-4bf22.firebaseapp.com',
    storageBucket: 'surtte-4bf22.firebasestorage.app',
    measurementId: 'G-WVSCGW72SN',
  );
}
